// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiyXyRPkSv7zz6m9xVQVfedwJyCnYBUnk',
    appId: '1:108541610056:web:9da2a3f8d94414a3afb07d',
    messagingSenderId: '108541610056',
    projectId: 'sfip-tasks-58a1c',
    authDomain: 'sfip-tasks-58a1c.firebaseapp.com',
    databaseURL: 'https://sfip-tasks-58a1c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sfip-tasks-58a1c.firebasestorage.app',
    measurementId: 'G-5K76Y89ZTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4YG6UWzn_aL_o5hjA1nZxTTi26Pd7vNI',
    appId: '1:108541610056:android:614bd290217b545eafb07d',
    messagingSenderId: '108541610056',
    projectId: 'sfip-tasks-58a1c',
    databaseURL: 'https://sfip-tasks-58a1c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sfip-tasks-58a1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0FYOFM5Kc6aQU4XDDjTPAP46aG5wl9ag',
    appId: '1:108541610056:ios:de8f37d54ee6fe1cafb07d',
    messagingSenderId: '108541610056',
    projectId: 'sfip-tasks-58a1c',
    databaseURL: 'https://sfip-tasks-58a1c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sfip-tasks-58a1c.firebasestorage.app',
    iosBundleId: 'com.example.sfipTasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0FYOFM5Kc6aQU4XDDjTPAP46aG5wl9ag',
    appId: '1:108541610056:ios:de8f37d54ee6fe1cafb07d',
    messagingSenderId: '108541610056',
    projectId: 'sfip-tasks-58a1c',
    databaseURL: 'https://sfip-tasks-58a1c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sfip-tasks-58a1c.firebasestorage.app',
    iosBundleId: 'com.example.sfipTasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiyXyRPkSv7zz6m9xVQVfedwJyCnYBUnk',
    appId: '1:108541610056:web:1cc64fded8b1f6bcafb07d',
    messagingSenderId: '108541610056',
    projectId: 'sfip-tasks-58a1c',
    authDomain: 'sfip-tasks-58a1c.firebaseapp.com',
    databaseURL: 'https://sfip-tasks-58a1c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sfip-tasks-58a1c.firebasestorage.app',
    measurementId: 'G-MTMYMCSHZE',
  );
}
